-- This script was generated by the ERD tool in pgAdmin 4. 

-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps. 

BEGIN; 

  

  

CREATE TABLE IF NOT EXISTS public.detalle_pedido 

( 

    id integer NOT NULL DEFAULT nextval('detalle_pedido_id_seq'::regclass), 

    id_pedido integer NOT NULL, 

    id_producto integer NOT NULL, 

    cantidad_procucto integer NOT NULL, 

    subtotal integer NOT NULL, 

    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id) 

); 

  

CREATE TABLE IF NOT EXISTS public.pedido_compra 

( 

    id integer NOT NULL DEFAULT nextval('pedido_compra_id_seq'::regclass), 

    id_proveedor integer NOT NULL, 

    id_sucursal integer NOT NULL, 

    fecha_hora date NOT NULL, 

    total integer NOT NULL, 

    CONSTRAINT pedido_compra_pkey PRIMARY KEY (id) 

); 

  

CREATE TABLE IF NOT EXISTS public.productos 

( 

    id integer NOT NULL DEFAULT nextval('productos_id_seq'::regclass), 

    descripcion character varying COLLATE pg_catalog."default" NOT NULL, 

    cantidad_minima integer NOT NULL, 

    cantidad_stock integer NOT NULL, 

    precio_venta integer NOT NULL, 

    categoria character varying COLLATE pg_catalog."default" NOT NULL, 

    marca character varying COLLATE pg_catalog."default" NOT NULL, 

    estado character varying COLLATE pg_catalog."default" NOT NULL, 

    CONSTRAINT productos_pkey PRIMARY KEY (id) 

); 

  

CREATE TABLE IF NOT EXISTS public.proveedor 

( 

    id integer NOT NULL DEFAULT nextval('proveedor_id_seq'::regclass), 

    razon_social integer NOT NULL, 

    tipo_doc character varying COLLATE pg_catalog."default" NOT NULL, 

    numero_doc integer NOT NULL, 

    direccion character varying COLLATE pg_catalog."default" NOT NULL, 

    mail character varying COLLATE pg_catalog."default" NOT NULL, 

    celular integer NOT NULL, 

    estado character varying COLLATE pg_catalog."default" NOT NULL, 

    CONSTRAINT proveedor_pkey PRIMARY KEY (id) 

); 

  

CREATE TABLE IF NOT EXISTS public.sucursal 

( 

    id integer NOT NULL DEFAULT nextval('sucursal_id_seq'::regclass), 

    descripcion character varying COLLATE pg_catalog."default" NOT NULL, 

    telefono integer NOT NULL, 

    whatsapp integer NOT NULL, 

    mail character varying COLLATE pg_catalog."default" NOT NULL, 

    estado character varying COLLATE pg_catalog."default" NOT NULL, 

    CONSTRAINT sucursal_pkey PRIMARY KEY (id) 

); 

  

ALTER TABLE IF EXISTS public.detalle_pedido 

    ADD CONSTRAINT id_pedido FOREIGN KEY (id_pedido) 

    REFERENCES public.pedido_compra (id) MATCH SIMPLE 

    ON UPDATE NO ACTION 

    ON DELETE NO ACTION; 

  

  

ALTER TABLE IF EXISTS public.detalle_pedido 

    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto) 

    REFERENCES public.productos (id) MATCH SIMPLE 

    ON UPDATE NO ACTION 

    ON DELETE NO ACTION; 

  

  

ALTER TABLE IF EXISTS public.pedido_compra 

    ADD CONSTRAINT id_proveedor FOREIGN KEY (id_proveedor) 

    REFERENCES public.proveedor (id) MATCH SIMPLE 

    ON UPDATE NO ACTION 

    ON DELETE NO ACTION; 

  

  

ALTER TABLE IF EXISTS public.pedido_compra 

    ADD CONSTRAINT id_sucursal FOREIGN KEY (id_sucursal) 

    REFERENCES public.sucursal (id) MATCH SIMPLE 

    ON UPDATE NO ACTION 

    ON DELETE NO ACTION; 

  

END; 